URL_CONFIG:
  map:
    base_url : https://www.bestbuy.com/site
    category_extension : computer-cards-components
    sub_category_extension : video-graphics-cards
    aux_extensions : abcat0507002.c?id=abcat0507002
  
  utils:
    concat_str : /

DATA_FEATURES:
  main_features_set : [
    'title',
    'type',
    'model',
    'sku',
    'rating',
    'reviews',
    'price',
    'availability',
    'link',
    'scraped_date'
    ]

  aux_features_set : [
  ]

DRIVER_OPTIONS:
  webdriver:
    chrome_driver_path: data\drivers\chrome\chromedriver.exe
  
  requests:
    args:
      headers:
        accept-language: en-US,en;q=0.9
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36